Translation languages are supported in the README file and all matched files use Prettier code style!
Grasscutters/Cultivation pull request #60
Opened 2022-08-08 03:04 UTC by Kawaa-qwq

Translation languages are supported in the README file and all matched files use Prettier code style!

2022-08-09 04:20 UTC, Kimi898246 commented
![image](https://user-images.githubusercontent.com/34180607/183563089-8a528512-c9c2-4980-9899-fd9721b6688a.png)
![image](https://user-images.githubusercontent.com/34180607/183563413-043e6a5b-c00f-41f0-821a-2f6de38c2cbb.png)

2022-08-09 05:19 UTC, Raymonf requested changes
looks ok but needs some vocab changes for the zh-TW readme

2022-08-09 05:19 UTC, Raymonf commented on README_zh-TW.md
> +對於遊戲版本為 2.8 及以上時，使用 Grasscutter 啟動時，Cultivation 會自動為您的遊戲客戶端製作一個小補丁，並在關閉遊戲時恢復它。 從理論上講，你應該是完全安全的，但是不明確**如果您使用它連接到官方服務器，修改遊戲客戶端可能會導致封號**，但可能性是非常小的，並且從未接到發生過此類情況的問題，但存在這種可能性！
* 補丁 -> 修補
* 服務器 -> 伺服器

2022-08-09 05:19 UTC, Raymonf commented on README_zh-TW.md
> +一個遊戲啟動器，旨在輕松將某動漫遊戲的流量代理到私人服務器。
服務器 -> 伺服器

2022-08-09 05:19 UTC, Raymonf commented on README_zh-TW.md
> +糾錯, 修復（一些）錯誤:
標點符號不一致

2022-08-09 05:19 UTC, Raymonf commented on README_zh-TW.md
> +- 將 `TAURI_PRIVATE_KEY` 添加到環境變量，其中包含私鑰的路徑。
環境變量 -> 環境變數

2022-08-10 04:24 UTC, Kawaa-qwq commented
ok，i will fix it

2022-08-22 05:52 UTC, Kawaa-qwq commented
I fix it

2022-08-27 08:01 UTC, merged